### ISSUE TITLE
'image' must be three-dimensional

### ISSUE THREAD

**Issue by chikiuso** [carpedm20/BEGAN-tensorflow#2]
Hi, sorry to interrupt you , I got another problem when running the program as follows : 

Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main(config)
  File "main.py", line 28, in main
    config.data_format, config.split)
  File "/home/chikiuso/Downloads/BEGAN-tensorflow/data_loader.py", line 48, in get_loader
    queue = tf.image.crop_to_bounding_box(queue, 50, 25, 128, 128)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 473, in crop_to_bounding_box
    assert_ops += _Check3DImage(image, require_static=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 131, in _Check3DImage
    raise ValueError("'image' must be three-dimensional.")
ValueError: 'image' must be three-dimensional.

**Comment by carpedm20** [comment]
You need to install nightly build of TensorFlow as I mentioned in README.md. See [README.md](https://github.com/tensorflow/tensorflow) of TensorFlow.

![image](https://cloud.githubusercontent.com/assets/3346407/24811744/45028c3e-1c02-11e7-8047-7997533b0ce1.png)

**Comment by fwiffo** [comment]
You can also use tf.map_fn; something like:
tf.map_fn(lambda i: tf.image.crop_to_bounding_box(i, 50, 25, 128, 128), queue)

**Comment by dribnet** [comment]
The following nightly worked for me (linux/gpu):

```bash
pip install --ignore-installed --upgrade \
http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.1.0rc1-cp27-cp27mu-linux_x86_64.whl
```

**Comment by zhangqianhui** [comment]
@fwiffo  thank you

**Comment by surya501** [comment]
I am using python3.6 & tensorflow 1.01. I dont want to upgrade yet, so was trying to work with minor modifications. For anyone else using this on older tensorflow + newer python, below are my edits to get it running.

 In addition to @fwiffo edits above, I also had to change import StringIO to import io in trainer.py. 

Also for some reason, I had to cast np.prod([8, 8, hidden_num]) to an int like int(np.prod([8, 8, hidden_num])) twice in models.py (line 7, line 39 as of now)

**Comment by nastyad** [comment]
The built @dribnet mentioned worked for me, but I used a different url
`https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/499/artifact/pip_test/whl/tensorflow_gpu-1.1.0-cp27-cp27mu-linux_x86_64.whl`
