### ISSUE TITLE
ValueError: last dimension shape must be known but is None?

### ISSUE THREAD

**Issue by lensea** [carpedm20/BEGAN-tensorflow#20]
This is the problem that came up in the first place. So I printed some information and positioned it here. Can you tell me why?Thank you!!!  I use my own database and tensorflow 0.10.0. 
from tranier.py:
self.z:	
Tensor("random_uniform:0", shape=(?, ?), dtype=float32)
from models.py :
self.z:
Tensor("random_uniform:0",  shape=(?, _?),_ dtype=float32)

Here is the complete error message:

root:	/media/z/lhj/images/testData_aligned/testData_aligned/
[16, 64, 64, 3]
3 64 64
self.data_loader:
Tensor("ToFloat:0", shape=(16, 3, 64, 64), dtype=float32)
self.z_num:
64
trainer x:
Tensor("sub:0", shape=(16, 3, 64, 64), dtype=float32)
tf.shape(x)[0]:
Tensor("strided_slice:0", shape=(), dtype=int32)
self.z:	
Tensor("random_uniform:0", shape=(?, ?), dtype=float32)
self.conv_hidden_num:	
128
self.channel:	
3
self.repeat_num:	
4
self.data_format:	
NCHW
from models begin:	
num_output:
8192
z:
Tensor("random_uniform:0", shape=(?, ?), dtype=float32)
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main(config)
  File "main.py", line 32, in main
    trainer = Trainer(config, data_loader_)
  File "/home/lhj/software/BEGAN-tensorflow-master/trainer.py", line 93, in __init__
    self.build_model()
  File "/home/lhj/software/BEGAN-tensorflow-master/trainer.py", line 199, in build_model
    self.repeat_num, self.data_format, reuse=False)
  File "/home/lhj/software/BEGAN-tensorflow-master/models.py", line 13, in GeneratorCNN
    x = slim.fully_connected(z, num_output, activation_fn=None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 792, in fully_connected
    num_input_units = utils.last_dimension(inputs_shape, min_rank=2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/utils.py", line 199, in last_dimension
    raise ValueError('last dimension shape must be known but is None')
ValueError: last dimension shape must be known but is None

**Comment by ysuzalmon** [comment]
I have the same problem!

**Comment by ysuzalmon** [comment]
And another problem is here:

Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main(config)
  File "main.py", line 28, in main
    config.data_format, config.split)
  File "/home/mrright/Public/BEGAN-tensorflow-master-out/data_loader.py", line 22, in get_loader
    with Image.open(paths[0]) as img:
IndexError: list index out of range

**Comment by lensea** [comment]
your root path was wrong .
You can try to correct it at downloader.py
if dataset_name in ['CelebA'] and split:
        root ="/media/z/lhj/images/celebA/img_align_celeba/" #your dataset path
        #root = os.path.join(root, 'splits', split)
    else:
        root="/media/z/lhj/images/testData_aligned/testData_aligned/"

**Comment by yaxingwang** [comment]
Hi@lensea, I have similar problem. Do you get it ? according to the readme, the reason maybe the low version of tensorflow, for I the code in different versions of tf, the latest version is ok, but for the low one, I have similar trouble. In fact, I compared the corresponding code (such as slim.fully_connected() with different versions, what I found is same based on the note, so I am not sure about this.

**Comment by lensea** [comment]
@yaxingwang thank you for you reply ! I run the program ,with  a few modifications ,at win10,tensorflow(1.1.0) and python3.5.3. As you say,the reason maybe the low version of tensorflow.

**Comment by yaxingwang** [comment]
@lensea ,Yes. I am trying to make modification to adjust to the low version. good luck.

**Comment by yaxingwang** [comment]
Hi @lensea, I have modified the program working in low version(0.11), if you want I cam share with you.

**Comment by lensea** [comment]
@yaxingwang Can you share me a copy of the program, that's better！ thank you ! My email is lensea@163.com !

**Comment by yaxingwang** [comment]
@lensea I have shared with you. please check it

**Comment by lensea** [comment]
Thank you very much！@yaxingwang

**Comment by kuabhish** [comment]
Share it to me Please

**Comment by chandanchinta** [comment]
> Hi @lensea, I have modified the program working in low version(0.11), if you want I cam share with you.

Please share the code with me too. Thank you.

**Comment by lensea** [comment]
This project has been over for a long time, and I have no code ! Sorry, I can't help you ! @chandanchinta

**Comment by chandanchinta** [comment]
> This project has been over for a long time, and I have no code ! Sorry, I can't help you ! @chandanchinta

okay thank you. If you stumble upon any time please share it.
