### ISSUE TITLE
Unable to train datasets

### ISSUE THREAD

**Issue by molyswu** [carpedm20/BEGAN-tensorflow#8]
Hi, 
I put the datasets in the data file,
and execute this command：$python main.py --dataset=CelebA --use_gpu=True ,The following bug:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from trainer import Trainer
  File "E:\product\faceVerification\faceAttributes\BEGAN-tensorflow\trainer.py", line 4, in <module>
    import StringIO
ImportError: No module named 'StringIO'

Thank you for your help!

**Comment by carpedm20** [comment]
Are you using python3?

**Comment by molyswu** [comment]
yes

**Comment by molyswu** [comment]
StringIO   Change io

**Comment by molyswu** [comment]
Hi,
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main(config)
  File "main.py", line 28, in main
    config.data_format, config.split)
  File "E:\product\faceVerification\faceAttributes\BEGAN-tensorflow\data_loader.py", line 22, in get_loader
    with Image.open(paths[0]) as img:
IndexError: list index out of range
Thank you for your help!

**Comment by molyswu** [comment]
![16](https://cloud.githubusercontent.com/assets/11438784/24993156/b69fb87c-2057-11e7-865a-7a25475b65cc.png)

**Comment by carpedm20** [comment]
Did you run this?

    python download.py

**Comment by molyswu** [comment]
I could download CelebA dataset using Baidu Drive.

**Comment by carpedm20** [comment]
The error said that data_loader.py couldn't find the images. You need to put `*.jpg` into `BEGAN-tensorflow/data/CelebA/*.jpg`.

**Comment by molyswu** [comment]
Hi,

![45](https://cloud.githubusercontent.com/assets/11438784/24996711/7d1bb54c-2066-11e7-8456-a7fde65d20ec.png)
Thank you for your help!

**Comment by molyswu** [comment]
Hi,
![Uploading 21.png…]()


Thank you for your help!

**Comment by molyswu** [comment]
Hi,


![Uploading 21.png…]()


Thank you for your help!
